version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tshirtlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/workspace/app/src
      - ~/.m2:/root/.m2:Z
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - env.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/tshirtlab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SERVER_FORWARD_HEADERS_STRATEGY: native

volumes:
  pgdata:
