app:
  aws:
    region: ${AWS_REGION}
    bucket: ${S3_BUCKET}
    base-url: ${SITE_BASE_URL}

  frontend-origin: ${FRONTEND_ORIGIN:http://localhost:3000}

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  config:
    import: "optional:env[.]properties"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false

  web:
    cors:
      mappings:
        "[/api/**]":
          allowed-origins: ${app.frontend-origin}
          allowed-methods: GET,POST,PUT,DELETE,OPTIONS
          allowed-headers: "*"
          allow-credentials: true
  application:
    name: tshirt-lab-backend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
        provider:
          google:
            issuer-uri: https://accounts.google.com
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
